#!/bin/bash

DBNAME=meri
HOST=localhost
PORT=5432
USER=$1
PW=$2

#cd sea
#
#for f in *.xml
#do 
#    ogr2ogr -f PostgreSQL -overwrite PG:"dbname='$DBNAME' host='$HOST' port='$PORT' user='$USER' password='$PW'" $f 
#done
#
#cd ../land

for f in *.xml
do
    ogr2ogr -f PostgreSQL -overwrite PG:"dbname='$DBNAME' host='$HOST' port='$PORT' user='$USER' password='$PW'" $f
done


